import { Cube } from './cube.ts'
import { Face } from "./face.ts";
import { Rotation } from "./rotation.ts";

const cube = new Cube();
cube.print2d();
console.log('===========');
cube.rotate(Face.top, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.top, Rotation.counterclockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.left, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.left, Rotation.counterclockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.front, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.front, Rotation.counterclockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.right, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.right, Rotation.counterclockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.back, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.back, Rotation.counterclockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.down, Rotation.clockwise);
cube.print2d();
console.log('===========');
cube.rotate(Face.down, Rotation.counterclockwise);
cube.print2d();
