name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.34.2"
      - name: build
        env:
          BASE_PATH: "/RubiksCube"
        run: |
          deno task build
          sed 's/"\/cube-favicon.png/"\/RubiksCube\/cube-favicon.png/' -i dist/index.html
          sed 's/"\/assets/"\/RubiksCube\/assets/' -i dist/index.html
          touch dist/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
